# Generated by Django 4.2 on 2023-06-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verify_link',
            old_name='link',
            new_name='rnd_no',
        ),
    ]
