# Generated by Django 4.2 on 2023-06-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_link_verify_link_rnd_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='verify_link',
            new_name='otp',
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='rnd_no',
            new_name='otp',
        ),
    ]
