# Generated by Django 4.2 on 2023-06-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_verify_link_otp_rename_rnd_no_otp_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='otp_no',
        ),
    ]
