# Generated by Django 4.2 on 2023-06-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_menu'),
        ('home', '0004_rename_otp_otp_otp_no'),
    ]

    operations = [
    ]
